# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d877e1b967ac0007ef7d95521997d9e13c85ddd65e050f609de5002fad19772d09b491fd63176c4b48d5da4f88edc87784ddf3a0773aec8a4265e23d36a50b65

test:
  secret_key_base: 93f3c407bce2c98946c915c61bfc06420c534bec3f7347116ac9645cc1ba308dad50f3f05beae9d97d3b81440c9779ed1e80f3f41fcce2436286e179cbab6cc5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
